config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#facebook_auth'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/', to: 'sessions#welcome'
  get '/home', to: 'sessions#home'
  delete '/session', to: 'sessions#destroy'
  get '/users/:user_id/cocktails', to: 'users#user_cocktails_index'
  get '/users/:user_id/reviewed_cocktails', to: 'users#reviewed_cocktails'

  resources :ingredients
  resources :users, only: [:new, :create]

  resources :cocktails do
    resources :reviews
  end

 



end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    has_many :cocktail_ingredients
    has_many :ingredients, through: :cocktail_ingredients
    has_many :user_cocktails
    has_many :users, through: :user_cocktails
    has_many :reviews
    has_many :user_reviews, through: :reviews, source: :users
    #accepts_nested_attributes_for :ingredient_ids #, reject_if: proc { |ing| ing["name"] == "" }
    validates :name, uniqueness: true
    validates_presence_of :name, :recipe, :calories 
    validates_presence_of :ingredients
    validates :name, length: { in: 2..20 }
    scope :search, -> (query) { where("LOWER(name) LIKE ?", "%#{query.downcase}%") }




    def can_edit?(user)
        user.in?(self.users)
    end

end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
    before_action :require_login
    before_action :find_cocktail, only: [:show, :edit, :update, :destroy]
    before_action :authorized?, only: [:edit, :update, :destroy]

    def index
        if params[:ingredient_id].present?
            ingredient = Ingredient.find_by_id(params[:ingredient_id])
            @cocktails = ingredient.cocktails
        else
            @cocktails = Cocktail.all
        end
        if params[:search].present?
            @cocktails = @cocktails.search(params[:search])
        end
        @cocktails = @cocktails.order(:name)
    end

    def show
            if @cocktail
                render :show
            else
                flash[:notice] = "Cocktail not found!"
                redirect_to cocktails_path
            end
        end

    def new
        @cocktail = Cocktail.new
    end

    def create
        @cocktail = current_user.cocktails.create(cocktail_params)
        if @cocktail.persisted?
            redirect_to @cocktail
        else
            flash.now[:notice] = @cocktail.errors.full_messages.to_sentence
            render :new
        end
    end

    def edit
    end

    def update
        @cocktail.update(cocktail_params)
        if @cocktail.errors.empty?
            redirect_to @cocktail
        else
            flash.now[:notice] = @cocktail.errors.full_messages.to_sentence
            render :edit
        end
    end

    def destroy
        if @cocktail.destroy
            redirect_to cocktails_path
        else
            flash[:notice] = "Was unable to delete Cocktail"
            redirect_to @cocktail
        end
    end


    private

    def find_cocktail
        @cocktail = Cocktail.find_by(id: params[:id])
    end

    def cocktail_params
        params.require(:cocktail).permit(:name, :recipe, :calories, :comment, ingredient_ids:[])
    end

    def authorized?
        if !@cocktail.can_edit?(current_user)
            head :unauthorized
        end
    end


end

app/helpers/cocktails_helper.rb
module CocktailsHelper

    # def formatted_date(cocktail)
    #     cocktail.created_at.strftime("%a, %e %b %Y %H:%M")
    # end
end

app/views/cocktails/_form.html.erb
<%= form_with model:@cocktail, local: :true do |form| %>
    <p> 
    <%= form.label :name%><br>
    <%= form.text_field :name, class: @cocktail.errors[:name].present? ? "custom_errors" : nil %></p>
    <br>
    <%= form.label :calories%><br>
    <p><%= form.number_field :calories, class: @cocktail.errors[:calories].present? ? "custom_errors" : nil %></p>  
    <br>
    <%= form.label :recipe%><br>
    <p><%= form.text_area :recipe, class: @cocktail.errors[:recipe].present? ? "custom_errors" : nil %></p>
    <br>
    <p><%= form.label :ingredients%></p>
    <p> * command + click to select multiple ingredients *</p>
    <%= form.collection_select(:ingredient_ids, Ingredient.order(:name).all, :id, :name, {}, {multiple:true, class: @cocktail.errors[:ingredients].present? ? "custom_errors" : nil })%>
    <br>
    <p>Didn't see an ingredient you need?</p>
    <%=link_to "Add an Ingredient!", new_ingredient_path%>
    <br>
    <br>
    <%= form.submit %>
<% end %>

app/views/cocktails/edit.html.erb
<section class="jumbotron text-center">
    <div class="container">
    <h1>Edit your cocktail</h1>
    <%= render 'form' %>

    </div>
</section>

app/views/cocktails/index.html.erb
<section class="jumbotron text-center">
    <div class="container">
<%= form_with url:'/cocktails', method: "get", local: true do %>
    <%=select_tag 'ingredient_id', options_from_collection_for_select(Ingredient.order(:name).all, :id, :name, params[:ingredient_id]), prompt:"Choose an ingredient"%>
    <%= text_field_tag :search, params[:search], placeholder: "Cocktail Name"%>
    <%= submit_tag "Search"%>
<% end %>
<br>
<% if params[:search] %>
    <h1>Your Seach Results:</h1>
    <%if @cocktails.empty? %>
        <h4>There are no cocktails found<h4>
    <% end %>
<% else %>
    <h1> All Cocktails! </h1>
<% end %>
 <% @cocktails.each do |cocktail| %>
    <li> <%= link_to cocktail.name, cocktail_path(cocktail) %></li>
<% end %>
<section class="jumbotron text-center">
    <div class="container">

app/views/cocktails/new.html.erb
<section class="jumbotron text-center">
    <div class="container">
    <h1>Add a new cocktail</h1>
        <%= render 'form' %>
<section class="jumbotron text-center">
    <div class="container">

app/views/cocktails/show.html.erb
<section class="jumbotron text-center">
    <div class="container">

<h1> Recipe for <%= @cocktail.name %> </h1>
<br>
<label> Name: </label>
<h4><%=@cocktail.name %></h4>
<label> Calories: </label>
<h4><%=@cocktail.calories %></h4>
<label> Ingredients: </label>
<% @cocktail.ingredients.each do |ing| %>
    <h5><li><%= ing.name %></li></h5>
    <% end %>
<br> 
<h4>Recipe: </h4>
 <p><%=@cocktail.recipe %></p>
 <br> 
<h4>Average Rating out of 10: </h4>
 <p><%=@cocktail.reviews.average(:rating).try(:round, 1) || 'Not yet rated' %></p>

 <% if @cocktail.can_edit?(current_user) %>
<h6>
    <a href=<%=edit_cocktail_path(@cocktail)%> class="btn btn-secondary my-2" style="background-color:black;border-color:black;">Edit</a>
</h6>
<h6>
    <%= button_to "Delete", @cocktail, method: :delete, data: {confirm: "Delete this cocktail?"} %>

</h6>
<% else %>
    <% review = current_user.reviews.where(cocktail: @cocktail).first %>
    <% if review %>
        <h4> Your rating for this cocktail: </h4>
        <p><%= review.rating %></p>
    <% else %>
<h6>
    <a href=<%=new_cocktail_review_path(@cocktail)%> class="btn btn-secondary my-2" style="background-color:black;border-color:black;">Add a review</a>
</h6>
    <% end %>
<% end %>

    </div>
</section>